[Logo-menu]
hide-forcequit=true
hide-icon-shadow=false
hide-softwarecentre=false
menu-button-extensions-app='org.gnome.Extensions.desktop'
menu-button-icon-image=0
menu-button-software-center='snap-store'
menu-button-system-monitor='resources'
menu-button-terminal='ptyxis'
show-activities-button=false
show-lockscreen=true
show-power-options=false
symbolic-icon=true
use-custom-icon=false

[appindicator]
icon-brightness=0.0
icon-contrast=0.0
icon-opacity=240
icon-saturation=0.0
icon-size=0

[blur-my-shell]
rounded-blur-found=false
settings-version=2

[blur-my-shell/appfolder]
brightness=0.59999999999999998
sigma=30

[blur-my-shell/applications]
blur=false
opacity=255
pipeline='pipeline_default'
static-blur=false

[blur-my-shell/coverflow-alt-tab]
pipeline='pipeline_default'

[blur-my-shell/dash-to-dock]
blur=true
brightness=0.59999999999999998
override-background=true
pipeline='pipeline_default_rounded'
sigma=30
static-blur=true
style-dash-to-dock=0

[blur-my-shell/dash-to-panel]
blur-original-panel=true

[blur-my-shell/hidetopbar]
compatibility=false

[blur-my-shell/lockscreen]
pipeline='pipeline_default_rounded'

[blur-my-shell/overview]
pipeline='pipeline_default_rounded'

[blur-my-shell/panel]
blur=true
brightness=0.59999999999999998
corner-radius=32
force-light-text=false
override-background=true
override-background-dynamically=true
pipeline='pipeline_default_rounded'
sigma=30
static-blur=true
unblur-in-overview=false

[blur-my-shell/screenshot]
pipeline='pipeline_default_rounded'

[blur-my-shell/window-list]
brightness=0.59999999999999998
sigma=30

[dash-to-dock]
always-center-icons=true
apply-custom-theme=false
autohide=false
background-opacity=0.14999999999999999
custom-theme-shrink=true
customize-alphas=true
dash-max-icon-size=48
disable-overview-on-startup=true
dock-fixed=false
dock-position='BOTTOM'
extend-height=false
height-fraction=0.90000000000000002
hot-keys=true
intellihide=true
intellihide-mode='ALL_WINDOWS'
max-alpha=0.94999999999999996
min-alpha=0.40000000000000002
preferred-monitor=-2
preferred-monitor-by-connector='Virtual-1'
require-pressure-to-show=false
show-apps-at-top=true
show-dock-urgent-notify=false
transparency-mode='DYNAMIC'

[ding]
arrangeorder='KIND'
check-x11wayland=true
dark-text-in-labels=true
keep-arranged=true
keep-stacked=true
show-network-volumes=true
show-trash=false
show-volumes=true
sort-special-folders=true
start-corner='top-left'

[sysmon]
monochrome-mode=false
show-swap=false

[system-monitor]
cpu-meter=false
layout='vertical'
memory-meter=false
position='center'

[tiling-assistant]
focus-hint-color='rgb(203,67,20)'
last-version-installed=54
overridden-settings={'org.gnome.mutter.edge-tiling': <@mb nothing>, 'org.gnome.mutter.keybindings.toggle-tiled-left': <@mb nothing>, 'org.gnome.mutter.keybindings.toggle-tiled-right': <@mb nothing>}
tiling-popup-all-workspace=true

[user-theme]
name='MacTahoe-Dark'

[utcclock]
show-seconds=false
